/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Fan;
import javax.swing.*;
import java.awt.*;
import java.awt.GradientPaint;
import java.awt.event.*;
import view.MatchBookingPage;
import view.MerchandisePage;
import view.PlayerStatisticsPage;
import view.FundraisingPage;
import view.LoginPage;
import view.TransactionsPage;






/**
 *
 * @author Hey
 */
public class FanDashboard extends javax.swing.JFrame {
private Fan fan;

    FanDashboard(int fanId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
class GradientPanel extends JPanel {
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Color color1 = new Color(0, 32, 91);  // Dark blue
        Color color2 = new Color(0, 102, 0);  // Rwanda green
        GradientPaint gp = new GradientPaint(0, 0, color1, getWidth(), getHeight(), color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }
}
    /**
     * Creates new form FanDashboard
     */
    public FanDashboard(Fan fan) {
        this.fan = fan;
        initComponents();
        setLocationRelativeTo(null);
        welcomeLabel.setText("Welcome, " + fan.getName());
        tierLabel.setText(fan.getTier() + " Member");
        
        // Set window title based on role
        if ("Admin".equalsIgnoreCase(fan.getRole())) {
            setTitle("FanHub - Admin Dashboard");
        } else {
            setTitle("FanHub - Fan Dashboard");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new  GradientPanel();
        jPanel1 = new javax.swing.JPanel();
        bookTicketsButton = new javax.swing.JButton();
        fundraisingButton = new javax.swing.JButton();
        viewPlayersButton = new javax.swing.JButton();
        viewMerchButton = new javax.swing.JButton();
        viewTransactionsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        tierLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FanHub - Dashboard");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 102));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        mainPanel.setPreferredSize(new java.awt.Dimension(440, 600));

        jPanel1.setBackground(new java.awt.Color(213, 233, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));

        bookTicketsButton.setBackground(new java.awt.Color(0, 75, 14));
        bookTicketsButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bookTicketsButton.setForeground(new java.awt.Color(255, 255, 255));
        bookTicketsButton.setText("BOOK MATCH TICKETS");
        bookTicketsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookTicketsButton.setMaximumSize(new java.awt.Dimension(300, 45));
        bookTicketsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketsButtonActionPerformed(evt);
            }
        });

        fundraisingButton.setBackground(new java.awt.Color(0, 75, 14));
        fundraisingButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fundraisingButton.setForeground(new java.awt.Color(255, 255, 255));
        fundraisingButton.setText("FUNDRAISE FOR TEAM");
        fundraisingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fundraisingButton.setMaximumSize(new java.awt.Dimension(300, 45));
        fundraisingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundraisingButtonActionPerformed(evt);
            }
        });

        viewPlayersButton.setBackground(new java.awt.Color(0, 75, 14));
        viewPlayersButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewPlayersButton.setForeground(new java.awt.Color(255, 255, 255));
        viewPlayersButton.setText("PLAYER STATISTICS");
        viewPlayersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPlayersButton.setMaximumSize(new java.awt.Dimension(300, 45));
        viewPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlayersButtonActionPerformed(evt);
            }
        });

        viewMerchButton.setBackground(new java.awt.Color(0, 75, 14));
        viewMerchButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewMerchButton.setForeground(new java.awt.Color(255, 255, 255));
        viewMerchButton.setText("VIEW MERCHANDISE");
        viewMerchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewMerchButton.setMaximumSize(new java.awt.Dimension(300, 45));
        viewMerchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMerchButtonActionPerformed(evt);
            }
        });

        viewTransactionsButton.setBackground(new java.awt.Color(0, 75, 14));
        viewTransactionsButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewTransactionsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewTransactionsButton.setText("VIEW TRANSACTIONS");
        viewTransactionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTransactionsButton.setMaximumSize(new java.awt.Dimension(300, 45));
        viewTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fundraisingButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(viewPlayersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookTicketsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMerchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewTransactionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bookTicketsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(viewMerchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(viewPlayersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(fundraisingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(viewTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 209, 0));
        jLabel1.setText("AMAVUBI FANHUB");

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome, [fan name]");

        tierLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tierLabel.setForeground(new java.awt.Color(200, 200, 200));
        tierLabel.setText("[fan tier] Member");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(180, 180, 180));
        jLabel4.setText("© 2025 Amavubi FanHub - Official Fan Platform");

        logoutButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 206, 0));
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutButton)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeLabel)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tierLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketsButtonActionPerformed
        // TODO add your handling code here:
        new MatchBookingPage(fan).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bookTicketsButtonActionPerformed

    private void viewMerchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMerchButtonActionPerformed
        // TODO add your handling code here:
        new MerchandisePage(fan).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_viewMerchButtonActionPerformed

    private void viewPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlayersButtonActionPerformed
        // TODO add your handling code here:
         new PlayerStatisticsPage(fan).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_viewPlayersButtonActionPerformed

    private void fundraisingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundraisingButtonActionPerformed
        // TODO add your handling code here:
         new FundraisingPage(fan).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_fundraisingButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
         new LoginPage().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionsButtonActionPerformed
        // TODO add your handling code here:
     new TransactionsPage(fan).setVisible(true);
this.dispose(); // This line prevents coming back!
// Optional: close current dashboard if desired
    }//GEN-LAST:event_viewTransactionsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTicketsButton;
    private javax.swing.JButton fundraisingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel tierLabel;
    private javax.swing.JButton viewMerchButton;
    private javax.swing.JButton viewPlayersButton;
    private javax.swing.JButton viewTransactionsButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}

// Amavubi auto-commit #0 - 11/02/2025 02:05:39
// Amavubi auto-commit #1 - 11/02/2025 02:05:41
// Amavubi auto-commit #2 - 11/02/2025 02:05:42
// Amavubi auto-commit #3 - 11/02/2025 02:05:42
// Amavubi auto-commit #4 - 11/02/2025 02:05:43
// Amavubi auto-commit #5 - 11/02/2025 02:05:43
// Amavubi auto-commit #6 - 11/02/2025 02:05:44
// Amavubi auto-commit #7 - 11/02/2025 02:05:44
// Amavubi auto-commit #8 - 11/02/2025 02:05:45
// Amavubi auto-commit #9 - 11/02/2025 02:05:45
// Amavubi auto-commit #10 - 11/02/2025 02:05:46
// Amavubi auto-commit #11 - 11/02/2025 02:05:46
// Amavubi auto-commit #12 - 11/02/2025 02:05:47
// Amavubi auto-commit #13 - 11/02/2025 02:05:47
// Amavubi auto-commit #14 - 11/02/2025 02:05:48
// Amavubi auto-commit #15 - 11/02/2025 02:05:48
// Amavubi auto-commit #16 - 11/02/2025 02:05:49
// Amavubi auto-commit #17 - 11/02/2025 02:05:49
// Amavubi auto-commit #18 - 11/02/2025 02:05:50
// Amavubi auto-commit #19 - 11/02/2025 02:05:50
// Amavubi auto-commit #20 - 11/02/2025 02:05:51
// Amavubi auto-commit #21 - 11/02/2025 02:05:51
// Amavubi auto-commit #22 - 11/02/2025 02:05:52
// Amavubi auto-commit #23 - 11/02/2025 02:05:53
// Amavubi auto-commit #24 - 11/02/2025 02:05:54
// Amavubi auto-commit #25 - 11/02/2025 02:05:54
// Amavubi auto-commit #26 - 11/02/2025 02:05:55
// Amavubi auto-commit #27 - 11/02/2025 02:05:55
// Amavubi auto-commit #28 - 11/02/2025 02:05:56
// Amavubi auto-commit #29 - 11/02/2025 02:05:56
// Amavubi auto-commit #30 - 11/02/2025 02:05:57
// Amavubi auto-commit #31 - 11/02/2025 02:05:57
// Amavubi auto-commit #32 - 11/02/2025 02:05:58
// Amavubi auto-commit #33 - 11/02/2025 02:05:59
// Amavubi auto-commit #34 - 11/02/2025 02:05:59
// Amavubi auto-commit #35 - 11/02/2025 02:05:59
// Amavubi auto-commit #36 - 11/02/2025 02:06:00
// Amavubi auto-commit #37 - 11/02/2025 02:06:01
// Amavubi auto-commit #38 - 11/02/2025 02:06:01
// Amavubi auto-commit #39 - 11/02/2025 02:06:01
// Amavubi auto-commit #40 - 11/02/2025 02:06:02
// Amavubi auto-commit #41 - 11/02/2025 02:06:03
// Amavubi auto-commit #42 - 11/02/2025 02:06:03
// Amavubi auto-commit #43 - 11/02/2025 02:06:04
// Amavubi auto-commit #44 - 11/02/2025 02:06:04
// Amavubi auto-commit #45 - 11/02/2025 02:06:05
// Amavubi auto-commit #46 - 11/02/2025 02:06:05
// Amavubi auto-commit #47 - 11/02/2025 02:06:06
// Amavubi auto-commit #48 - 11/02/2025 02:06:06
// Amavubi auto-commit #49 - 11/02/2025 02:06:07
// Amavubi auto-commit #50 - 11/02/2025 02:06:07
// Amavubi auto-commit #51 - 11/02/2025 02:06:08
// Amavubi auto-commit #52 - 11/02/2025 02:06:09
// Amavubi auto-commit #53 - 11/02/2025 02:06:09
// Amavubi auto-commit #54 - 11/02/2025 02:06:10
// Amavubi auto-commit #55 - 11/02/2025 02:06:10
// Amavubi auto-commit #56 - 11/02/2025 02:06:11
// Amavubi auto-commit #57 - 11/02/2025 02:06:11
// Amavubi auto-commit #58 - 11/02/2025 02:06:12
// Amavubi auto-commit #59 - 11/02/2025 02:06:12
// Amavubi auto-commit #60 - 11/02/2025 02:06:13
// Amavubi auto-commit #61 - 11/02/2025 02:06:13
// Amavubi auto-commit #62 - 11/02/2025 02:06:14
// Amavubi auto-commit #63 - 11/02/2025 02:06:15
// Amavubi auto-commit #64 - 11/02/2025 02:06:15
// Amavubi auto-commit #65 - 11/02/2025 02:06:16
// Amavubi auto-commit #66 - 11/02/2025 02:06:16
// Amavubi auto-commit #67 - 11/02/2025 02:06:17
// Amavubi auto-commit #68 - 11/02/2025 02:06:18
// Amavubi auto-commit #69 - 11/02/2025 02:06:18
// Amavubi auto-commit #70 - 11/02/2025 02:06:19
// Amavubi auto-commit #71 - 11/02/2025 02:06:19
// Amavubi auto-commit #72 - 11/02/2025 02:06:20
// Amavubi auto-commit #73 - 11/02/2025 02:06:20
// Amavubi auto-commit #74 - 11/02/2025 02:06:21
// Amavubi auto-commit #75 - 11/02/2025 02:06:21
// Amavubi auto-commit #76 - 11/02/2025 02:06:22
// Amavubi auto-commit #77 - 11/02/2025 02:06:22
// Amavubi auto-commit #78 - 11/02/2025 02:06:23
// Amavubi auto-commit #79 - 11/02/2025 02:06:23
// Amavubi auto-commit #80 - 11/02/2025 02:06:24
// Amavubi auto-commit #81 - 11/02/2025 02:06:24
// Amavubi auto-commit #82 - 11/02/2025 02:06:25
// Amavubi auto-commit #83 - 11/02/2025 02:06:25
// Amavubi auto-commit #84 - 11/02/2025 02:06:26
// Amavubi auto-commit #85 - 11/02/2025 02:06:26
// Amavubi auto-commit #86 - 11/02/2025 02:06:27
// Amavubi auto-commit #87 - 11/02/2025 02:06:28
// Amavubi auto-commit #88 - 11/02/2025 02:06:28
// Amavubi auto-commit #89 - 11/02/2025 02:06:29
// Amavubi auto-commit #90 - 11/02/2025 02:06:29
// Amavubi auto-commit #91 - 11/02/2025 02:06:30
// Amavubi auto-commit #92 - 11/02/2025 02:06:30
// Amavubi auto-commit #93 - 11/02/2025 02:06:31
// Amavubi auto-commit #94 - 11/02/2025 02:06:31
