/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Model.Fan;
import Dao.MatchDAO;
import Dao.TransactionDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
/**
 *
 * @author Hey
 */
public class MatchBookingPage extends javax.swing.JFrame {
     private Fan fan; 

    private MatchBookingPage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
class GradientPanel extends JPanel {
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Color color1 = new Color(0, 32, 91);  // Dark blue
        Color color2 = new Color(0, 102, 0);  // Rwanda green
        GradientPaint gp = new GradientPaint(0, 0, color1, getWidth(), getHeight(), color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }
}
    /**
     * Creates new form MatchBookingPage
     */
    public MatchBookingPage(Fan fan) {
        if (fan == null) {
        JOptionPane.showMessageDialog(null, 
            "Error: No fan data provided. Returning to login.",
            "System Error", 
            JOptionPane.ERROR_MESSAGE);
        // Optionally redirect to login
        new LoginPage().setVisible(true);
        return;
    }
    
    this.fan = fan;
    initComponents();
    setLocationRelativeTo(null);
    loadMatches();
    }
private void loadMatches() {
    MatchDAO matchDAO = new MatchDAO();
    matchComboBox.removeAllItems();
    String[] matches = matchDAO.getAvailableMatches();
    for (String match : matches) {
        matchComboBox.addItem(match);
    }
}   
    private void resetForm() {
    // Reset combo boxes to default values
    matchComboBox.setSelectedIndex(0);
    seatCategoryComboBox.setSelectedIndex(0);
    paymentMethodComboBox.setSelectedIndex(0);
    
    // Reload matches in case availability changed
    loadMatches();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new GradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matchComboBox = new javax.swing.JComboBox<>();
        seatCategoryComboBox = new javax.swing.JComboBox<>();
        confirmButton = new javax.swing.JButton();
        paymentMethodComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FanHub - Match Booking");
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 209, 0));
        jLabel1.setText("AMAVUBI FANHUB");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Match Ticket Booking");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT MATCH:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEAT CATEGORY:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PAYMENT METHOD:");

        matchComboBox.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        matchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6" }));

        seatCategoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        seatCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Regular", "Upbowl" }));

        confirmButton.setBackground(new java.awt.Color(0, 102, 0));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("CONFIRM BOOKING");
        confirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        paymentMethodComboBox.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        paymentMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MobileMoney", "Credit Card", "Cash" }));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("© 2025 Amavubi FanHub - Official Fan Platform");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 209, 0));
        jButton1.setText("Back to Dashboard");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paymentMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addComponent(jLabel1))
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(jLabel6)
                            .addGap(26, 26, 26)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(seatCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainpanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(matchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(seatCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(mainpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
         boolean isValid = true;
    String errorMessage = "";
    JComponent errorComponent = null;
    
    // Check match selection
    if (matchComboBox.getSelectedItem() == null || matchComboBox.getSelectedIndex() == 0) {
        isValid = false;
        errorMessage = "Please select a match from the list";
        errorComponent = matchComboBox;
    }
    // Check seat category selection
    else if (seatCategoryComboBox.getSelectedItem() == null || seatCategoryComboBox.getSelectedIndex() == 0) {
        isValid = false;
        errorMessage = "Please select a seat category";
        errorComponent = seatCategoryComboBox;
    }
    // Check payment method selection
    else if (paymentMethodComboBox.getSelectedItem() == null || paymentMethodComboBox.getSelectedIndex() == 0) {
        isValid = false;
        errorMessage = "Please select a payment method";
        errorComponent = paymentMethodComboBox;
    }
    
    // If any validation failed, show error and return
    if (!isValid) {
        showError(errorMessage);
        if (errorComponent != null) {
            errorComponent.requestFocusInWindow();
        }
        return;
    }

    // All validations passed - proceed with booking
    String selectedMatch = (String) matchComboBox.getSelectedItem();
    String selectedSeatCategory = (String) seatCategoryComboBox.getSelectedItem();
    String selectedPaymentMethod = (String) paymentMethodComboBox.getSelectedItem();

    try {
        // Additional validation for match format
        if (!selectedMatch.contains(" on ")) {
            showError("Invalid match format. Please select a valid match.");
            return;
        }

        // Rest of your existing booking logic...
        String[] matchDetails = selectedMatch.split(" on ");
        String opponent = matchDetails[0].replace("Rwanda vs ", "").trim();
        String matchDate = matchDetails[1].trim();

        MatchDAO matchDAO = new MatchDAO();
        int matchId = matchDAO.getMatchIdByOpponentAndDate(opponent, matchDate);

        if (matchId == -1) {
            showError("Selected match is no longer available.");
            return;
        }

        double ticketPrice = matchDAO.getTicketPriceByCategory(matchId, selectedSeatCategory);

        if (!matchDAO.updateAvailableSeats(matchId, selectedSeatCategory)) {
            showError("No available seats in " + selectedSeatCategory + " category.");
            return;
        }

        TransactionDAO transactionDAO = new TransactionDAO();
        boolean success = transactionDAO.insertMatchBooking(
            fan.getFanId(), 
            matchId, 
            ticketPrice, 
            selectedPaymentMethod
        );

        if (success) {
            showSuccess(selectedMatch, selectedSeatCategory, selectedPaymentMethod, ticketPrice);
            resetForm();
        } else {
            showError("Booking failed. Please try again.");
        }
    } catch (Exception e) {
        showError("An error occurred: " + e.getMessage());
    }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new FanDashboard(fan).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
private void showError(String message) {
  String htmlMessage = String.format(
        "<html><body style='width: 300px; padding: 10px;'>" +
        "<div style='color: #d8000c; background-color: #ffd2d2; padding: 10px; border-radius: 5px;'>" +
        "<h3 style='margin-top: 0;'>⚠️ Validation Error</h3>" +
        "<p>%s</p>" +
        "</div>" +
        "<p style='margin-top: 15px;'>Please correct the issue and try again.</p>" +
        "</body></html>",
        message
    );
    
    JOptionPane.showMessageDialog(this, 
        htmlMessage,
        "Validation Error", 
        JOptionPane.ERROR_MESSAGE);
}

private void showSuccess(String match, String seatCategory, String paymentMethod, double price) {
    String seatEmoji;
    switch (seatCategory) {
        case "VIP": seatEmoji = "💎"; break;
        case "Regular": seatEmoji = "🪑"; break;
        case "Upbowl": seatEmoji = "🌄"; break;
        default: seatEmoji = "🎟️";
    }

    String htmlMessage = String.format(
        "<html><body style='width: 320px;'>" +
        "<h2 style='color: #004696;'>🎟️ BOOKING CONFIRMED!</h2>" +
        "<p>Dear %s,</p>" +
        "<p>Your tickets are secured!</p>" +
        "<div style='border-top:1px solid #ccc; border-bottom:1px solid #ccc; padding:10px 0;'>" +
        "<p><b>%s</b></p>" +
        "</div>" +
        "<p>%s <b>%s</b></p>" +
        "<p>💳 <b>%s</b></p>" +
        "<p>💰 <b>$%.2f</b></p>" +
        "<h3 style='color: #004696;'>🎉 WE LOOK FORWARD TO SEEING YOU!</h3>" +
        "</body></html>",
        fan.getName(),
        match,
        seatEmoji,
        seatCategory,
        paymentMethod,
        price
    );

    JOptionPane.showMessageDialog(this, 
        htmlMessage,
        "Success", 
        JOptionPane.INFORMATION_MESSAGE);
}
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JComboBox<String> matchComboBox;
    private javax.swing.JComboBox<String> paymentMethodComboBox;
    private javax.swing.JComboBox<String> seatCategoryComboBox;
    // End of variables declaration//GEN-END:variables
}
